baseURL = "https://lepiej.social"
languageCode = "pl-PL"
title = "Lepiej."
publishDir = "public"
buildDrafts = false
buildFuture = false
enableRobotsTXT = true
enableGitInfo = false

[permalinks]
  about-me = "/about-me/"
  ugc = "/ugc/"
  social-media = "/social-media/"
  graphic-designs = "/graphic-designs/"


[params]
  description = "Lepiej. is a company that helps brands grow through social media. We create UGC, illustrations, design, branding, marketing, and audits."
  keywords = "Lepiej, social media, UGC, illustrations, design, branding, marketing, audit"
  author = "Lepiej Team"
  themeColor = "#98B4D4"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'